Mail and ocr
almutareb/mail_automation_wf pull request #12
Opened 2024-06-12 09:31 UTC by Xalt8

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Reviewers:

Please add the GitHub usernames of the reviewers:

- @username1
- @username2
- @username3

## Screenshots (if appropriate):

## Additional context

Add any other context or screenshots about the pull request here.

2024-06-12 09:33 UTC, Xalt8 commented
The summary function is working. The OCR for attachments is yet to be incorporated.

2024-06-12 23:10 UTC, isayahc requested changes
Nothing major just changing to make sure the paths works for other machines.

2024-06-12 23:10 UTC, isayahc commented on fetch_mail/Attachments/718ba392-d9e1-4e4b-80b3-b30809387e07_istockphoto-2149237610-1024x1024.jpg
could we add image to the `examples` directory.

2024-06-12 23:10 UTC, isayahc commented on fetch_mail/emails.json
for the file names. such as

`
"attachments": [
            "D:\\singh\\Documents\\Mail_Automation_WF\\mail_automation_wf\\Fetch Mail\\Attachments\\718ba392-d9e1-4e4b-80b3-b30809387e07_istockphoto-2149237610-1024x1024.jpg",
            "D:\\singh\\Documents\\Mail_Automation_WF\\mail_automation_wf\\Fetch Mail\\Attachments\\718ba392-d9e1-4e4b-80b3-b30809387e07_Sample filled Claim Form.pdf"
        ]`
Would we be able to turn this absolute path into a relative path like 


`"\\Mail_Automation_WF\\mail_automation_wf\\Fetch Mail\\Attachments\\718ba392-d9e1-4e4b-80b3-b30809387e07_Sample filled Claim Form.pdf"`

2024-06-13 10:25 UTC, Xalt8 commented
1. I've deleted the output_dir
2. The attachment location is not now relative referenced
3.  Added an image to examples
4. Changed the uuid identifier to use email entry id

2024-06-13 19:05 UTC, merged